name: 'Project board handler'
description: 'Handle issues and PRs in the project board'
inputs:
  token:
    description: 'Token for the repo with repo permissions'
    required: true
  owner:
    description: 'The owner of the project'
    required: true
  repo:
    description: 'The repo of the project'
    required: true
  project:
    description: 'The number of the project'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
