name: 'Project board handler'
description: 'Handle issues and PRs in the project board'
inputs:
  token:
    description: 'Token for the repo with repo permissions'
    required: true
  owner:
    description: 'The owner of the project'
    required: true
  repo:
    description: 'The repo of the project'
    required: true
  project:
    description: 'The number of the project'
    required: true
  columnbylabel:
    description: 'The destination Column by label, JSON format: &#39;{":bug: bug": "Urgent"}&#39;'
    required: false
  ignorecolumnnames:
    description: 'Columns to ignore when looking for a labeled issue card, comma separated: "Assigned,In progress,Review,Awaiting release,Last release"'
    required: false
  labelonclose:
    description: 'Label to add when issues and pull requests are closed'
    required: false
  moveonclose:
    description: 'Column to which issues should be moved when closed'
    required: false
  removeonclose:
    description: 'Column out of which issues should be removed when closed'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
